-- SQL COMMANDS  
-- Retrieve the total number of rentals made in the Sakila database 
Select count(rental_id) from rental; 

-- Find the average rental duration (in days) of movies rented from the Sakila database. 
select * from film;
select title, avg(rental_duration) from film group by film_id; 
 
 -- Display the first name and last name of customers in uppercase 
 select upper(first_name), upper(last_name) from customer; 
 
  --- Extract the month from the rental date and display it alongside the rental ID 
  select rental_id, month(rental_date) from rental; 
  
  -- Retrieve the count of rentals for each customer (display customer ID and the count of rentals
select * from rental;
select customer_id, count(rental_id) from rental group by customer_id; 

--- Find the total revenue generated by each store 
select store_id, sum(inventory_id) from inventory group by store_id;

-- Display the title of the movie, customer s first name, and last name who rented it 
select * from rental;
select first_name, last_name, f.title from customer inner join rental as r on customer.customer_id =r.customer_id 
inner join inventory as i on  i.inventory_id = r.inventory_id  inner join film as f on i.film_id = f.film_id;

-- Retrieve the names of all actors who have appeared in the film "Gone with the Wind." 
select * from film;
select actor.first_name,actor.last_name,title from film inner join film_actor on film_actor.film_id = film.film_id inner join actor 
on film_actor.film_id=film.film_id where title = 'ACADEMY DINOSAUR';

-- Determine the total number of rentals for each category of movies.
select * from rental;
select category_id, count(rental_id) from film_category join inventory as i on i.film_id = film_category.film_id
join rental as r on r.inventory_id = i.inventory_id group by category_id; 

--- Find the average rental rate of movies in each language 

select avg(rental_rate), language_id from film group by (language_id);

-- Retrieve the customer names along with the total amount they've spent on rentals. 
select * from payment;
select first_name, last_name, sum(amount), payment_id from customer join payment on payment.customer_id = customer.customer_id
group by payment_id;

-- List the titles of movies rented by each customer in a particular city (e.g., 'London'). 
select * from address;
select title from film where  film_id = (select film_id from inventory 
where inventory_id = (select inventory_id from rental where customer_id = (select customer_id from customer 
where address_id = ( select address_id from address where city_id = (select city_id from city where city  = 'london' group by city_id)))));

select title, r.rental_id, cy.city from film join inventory as i on i.film_id= film.film_id join rental as r on r.inventory_id = i.inventory_id 
join customer as c on c.customer_id = r.customer_id join address as a on a.address_id = c.address_id 
join city as cy on cy.city_id = a.city_id where city= 'london';

---- Display the top 5 rented movies along with the number of times they have been rented. 
select title, count(rental_id) from film join inventory as i on i.film_id = film.film_id join rental as r
on r.inventory_id = i.inventory_id group by rental_id limit 5 ; 

--- Determine the customers who have rented movies from both stores (store ID 1 and store ID 2) 
select * from rental;
select first_name, last_name, count(rental_id), s.store_id from customer as c join rental as r on r.customer_id = c.customer_id 
join inventory as i on i.inventory_id = r.inventory_id join store as s on s.store_id = i.store_id where s.store_id between 1 and 2  group by rental_id;